/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description API根路径
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查接口
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics
         * @description 获取性能指标
         */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Genes
         * @description 获取基因列表（支持分页和过滤）
         */
        get: operations["list_genes_api_v1_genes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genes/{gene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gene Detail
         * @description 获取基因详细信息（包含统计和直系同源基因）
         */
        get: operations["get_gene_detail_api_v1_genes__gene_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genes/{gene_id}/orthologs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gene Orthologs
         * @description 获取基因的直系同源基因列表
         */
        get: operations["get_gene_orthologs_api_v1_genes__gene_id__orthologs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Regulations
         * @description 获取调控关系列表（支持分页和过滤）
         */
        get: operations["list_regulations_api_v1_regulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regulations/{regulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regulation Detail
         * @description 获取调控关系详细信息
         */
        get: operations["get_regulation_detail_api_v1_regulations__regulation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regulations/gene/{gene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gene Regulations
         * @description 获取指定基因的所有调控关系（作为lncRNA）
         */
        get: operations["get_gene_regulations_api_v1_regulations_gene__gene_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diseases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Diseases
         * @description 获取疾病/性状列表（支持分页和过滤）
         */
        get: operations["list_diseases_api_v1_diseases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diseases/{trait_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Disease Detail
         * @description 获取疾病/性状详细信息
         */
        get: operations["get_disease_detail_api_v1_diseases__trait_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diseases/{trait_id}/genes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Disease Genes
         * @description 获取疾病关联的基因列表
         */
        get: operations["get_disease_genes_api_v1_diseases__trait_id__genes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diseases/gene/{gene_id}/associations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gene Disease Associations
         * @description 获取指定基因的所有疾病关联
         */
        get: operations["get_gene_disease_associations_api_v1_diseases_gene__gene_id__associations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview Stats
         * @description 获取全局概览统计
         */
        get: operations["get_overview_stats_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/top-genes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Genes
         * @description 获取Top基因（按调控关系数量排序）
         */
        get: operations["get_top_genes_api_v1_stats_top_genes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/top-diseases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top Diseases
         * @description 获取Top疾病（按关联基因数量排序）
         */
        get: operations["get_top_diseases_api_v1_stats_top_diseases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/conserved-regulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conserved Regulations
         * @description 获取保守调控关系（在多个物种中保守的lncRNA-target对）
         */
        get: operations["get_conserved_regulations_api_v1_stats_conserved_regulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/gene/{gene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gene Network
         * @description 获取基因的调控网络数据（用于Cytoscape可视化）
         *
         *     - gene_id: 中心基因ID
         *     - species_id: 限制物种（None表示所有物种）
         *     - min_ba: 最小结合亲和力
         *     - max_distance: 最大距离过滤
         *     - depth: 网络深度（1=直接调控，2=二度调控）
         */
        get: operations["get_gene_network_api_v1_network_gene__gene_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Species Networks
         * @description 跨物种网络对比
         *
         *     返回指定lncRNA在不同物种中的调控网络数据
         */
        get: operations["compare_species_networks_api_v1_network_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConservedRegulation
         * @description 保守调控关系
         */
        ConservedRegulation: {
            /** Lncrna Core Id */
            lncrna_core_id: number;
            /** Lncrna Name */
            lncrna_name: string | null;
            /** Target Core Id */
            target_core_id: number;
            /** Target Name */
            target_name: string | null;
            /**
             * Species Count
             * @description 保守物种数量
             */
            species_count: number;
            /**
             * Species List
             * @description 保守物种列表
             */
            species_list: string[];
            /** Avg Binding Affinity */
            avg_binding_affinity?: number | null;
        };
        /**
         * GeneDetail
         * @description 基因详细信息
         */
        GeneDetail: {
            /** Gene Id */
            gene_id: number;
            /** Core Id */
            core_id: number;
            /** Species Id */
            species_id: number;
            /** Species Name */
            species_name: string;
            /** Gene Name */
            gene_name?: string | null;
            /** Gene Ensembl Id */
            gene_ensembl_id?: string | null;
            /**
             * Gene Type
             * @description 基因类型（来自core_genes）
             */
            gene_type: string;
            /** Chromosome */
            chromosome?: string | null;
            /** Gene Start */
            gene_start?: number | null;
            /** Gene End */
            gene_end?: number | null;
            /** Strand */
            strand?: string | null;
            /**
             * Regulation Count
             * @description 调控关系数量
             * @default 0
             */
            regulation_count: number;
            /**
             * Target Count
             * @description 靶基因数量
             * @default 0
             */
            target_count: number;
            /**
             * Disease Count
             * @description 关联疾病数量
             * @default 0
             */
            disease_count: number;
            /** Orthologs */
            orthologs?: components["schemas"]["OrthologInfo"][];
            /** Created At */
            created_at?: string | null;
        };
        /**
         * GeneListItem
         * @description 基因列表项（用于列表展示）
         */
        GeneListItem: {
            /** Gene Id */
            gene_id: number;
            /** Core Id */
            core_id: number;
            /** Gene Name */
            gene_name?: string | null;
            /** Gene Ensembl Id */
            gene_ensembl_id?: string | null;
            /**
             * Gene Type
             * @description 基因类型（lncRNA/protein_coding）
             */
            gene_type: string;
            /** Species Name */
            species_name: string;
            /** Chromosome */
            chromosome?: string | null;
            /** Gene Start */
            gene_start?: number | null;
            /** Gene End */
            gene_end?: number | null;
            /**
             * Regulation Count
             * @description 调控关系数量
             * @default 0
             */
            regulation_count: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Redis */
            redis?: string | null;
            /** Version */
            version: string;
        };
        /**
         * NetworkData
         * @description 网络数据
         */
        NetworkData: {
            /** Nodes */
            nodes: components["schemas"]["NetworkNode"][];
            /** Edges */
            edges: components["schemas"]["NetworkEdge"][];
            /**
             * Stats
             * @description 网络统计信息
             */
            stats?: Record<string, never>;
        };
        /**
         * NetworkEdge
         * @description 网络边
         */
        NetworkEdge: {
            /**
             * Source
             * @description 源节点ID
             */
            source: string;
            /**
             * Target
             * @description 目标节点ID
             */
            target: string;
            /** Binding Affinity */
            binding_affinity?: number | null;
            /** Regulation Id */
            regulation_id: number;
        };
        /**
         * NetworkNode
         * @description 网络节点
         */
        NetworkNode: {
            /**
             * Id
             * @description 节点ID
             */
            id: string;
            /**
             * Label
             * @description 节点标签
             */
            label: string;
            /**
             * Type
             * @description 节点类型（lncRNA/protein_coding）
             */
            type: string;
            /** Gene Id */
            gene_id: number;
            /** Core Id */
            core_id: number;
        };
        /**
         * OrthologInfo
         * @description 直系同源基因信息
         */
        OrthologInfo: {
            /** Species Name */
            species_name: string;
            /** Species Id */
            species_id: number;
            /** Gene Id */
            gene_id: number;
            /** Gene Name */
            gene_name?: string | null;
            /** Gene Ensembl Id */
            gene_ensembl_id?: string | null;
            /** Chromosome */
            chromosome?: string | null;
            /** Gene Start */
            gene_start?: number | null;
            /** Gene End */
            gene_end?: number | null;
        };
        /**
         * OverviewStats
         * @description 全局概览统计
         */
        OverviewStats: {
            /**
             * Total Core Genes
             * @description 总核心基因数
             */
            total_core_genes: number;
            /**
             * Total Genes
             * @description 总基因数（含物种特异）
             */
            total_genes: number;
            /**
             * Total Lncrna
             * @description 总lncRNA数
             */
            total_lncrna: number;
            /**
             * Total Protein Coding
             * @description 总protein_coding基因数
             */
            total_protein_coding: number;
            /**
             * Total Regulations
             * @description 总调控关系数
             */
            total_regulations: number;
            /**
             * Total Traits
             * @description 总疾病/性状数
             */
            total_traits: number;
            /**
             * Total Trait Associations
             * @description 总疾病关联数
             */
            total_trait_associations: number;
            /** Species Stats */
            species_stats?: components["schemas"]["SpeciesStats"][];
            /** Database Version */
            database_version?: string | null;
            /** Last Updated */
            last_updated?: string | null;
        };
        /** PaginatedResponse[GeneListItem] */
        PaginatedResponse_GeneListItem_: {
            /**
             * Items
             * @description 数据列表
             */
            items: components["schemas"]["GeneListItem"][];
            /**
             * Total
             * @description 总记录数
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             */
            page_size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
        };
        /** PaginatedResponse[RegulationListItem] */
        PaginatedResponse_RegulationListItem_: {
            /**
             * Items
             * @description 数据列表
             */
            items: components["schemas"]["RegulationListItem"][];
            /**
             * Total
             * @description 总记录数
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             */
            page_size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
        };
        /** PaginatedResponse[TraitDetail] */
        PaginatedResponse_TraitDetail_: {
            /**
             * Items
             * @description 数据列表
             */
            items: components["schemas"]["TraitDetail"][];
            /**
             * Total
             * @description 总记录数
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             */
            page_size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
        };
        /** PaginatedResponse[TraitGeneAssociationDetail] */
        PaginatedResponse_TraitGeneAssociationDetail_: {
            /**
             * Items
             * @description 数据列表
             */
            items: components["schemas"]["TraitGeneAssociationDetail"][];
            /**
             * Total
             * @description 总记录数
             */
            total: number;
            /**
             * Page
             * @description 当前页码
             */
            page: number;
            /**
             * Page Size
             * @description 每页数量
             */
            page_size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
        };
        /**
         * RegulationDetail
         * @description 调控关系详细信息
         */
        RegulationDetail: {
            /** Regulation Id */
            regulation_id: number;
            /** Species Id */
            species_id: number;
            /** Species Name */
            species_name: string;
            /** Lncrna Gene Id */
            lncrna_gene_id: number;
            /** Lncrna Gene Name */
            lncrna_gene_name?: string | null;
            /** Lncrna Ensembl Id */
            lncrna_ensembl_id?: string | null;
            /** Target Gene Id */
            target_gene_id: number;
            /** Target Gene Name */
            target_gene_name?: string | null;
            /** Target Ensembl Id */
            target_ensembl_id?: string | null;
            /** Target Chromosome */
            target_chromosome?: string | null;
            /** Target Start */
            target_start?: number | null;
            /** Target End */
            target_end?: number | null;
            /** Tfo File */
            tfo_file?: string | null;
            /** Total Sites */
            total_sites?: number | null;
            /** Kept Sites */
            kept_sites?: number | null;
            /** Num Peaks */
            num_peaks?: number | null;
            /** Best Peak Num */
            best_peak_num?: number | null;
            /** Best Avg Ba */
            best_avg_ba?: string | null;
            /** Best Num Sites */
            best_num_sites?: number | null;
            /** Best Peak Chr */
            best_peak_chr?: string | null;
            /** Best Peak Start */
            best_peak_start?: number | null;
            /** Best Peak End */
            best_peak_end?: number | null;
            /** Best Site Ba */
            best_site_ba?: string | null;
            /** Lncrna Start */
            lncrna_start?: number | null;
            /** Lncrna End */
            lncrna_end?: number | null;
            /** Dna Start */
            dna_start?: number | null;
            /** Dna End */
            dna_end?: number | null;
            /** Binding Affinity */
            binding_affinity?: string | null;
            /** Lncrna Sequence */
            lncrna_sequence?: string | null;
            /** Dna Sequence */
            dna_sequence?: string | null;
        };
        /**
         * RegulationListItem
         * @description 调控关系列表项
         */
        RegulationListItem: {
            /** Regulation Id */
            regulation_id: number;
            /** Species Id */
            species_id: number;
            /** Species Name */
            species_name: string;
            /** Lncrna Gene Id */
            lncrna_gene_id: number;
            /** Lncrna Gene Name */
            lncrna_gene_name?: string | null;
            /** Target Gene Id */
            target_gene_id: number;
            /** Target Gene Name */
            target_gene_name?: string | null;
            /** Target Chromosome */
            target_chromosome?: string | null;
            /** Target Start */
            target_start?: number | null;
            /** Target End */
            target_end?: number | null;
            /** Binding Affinity */
            binding_affinity?: string | null;
            /** Best Avg Ba */
            best_avg_ba?: string | null;
            /** Num Peaks */
            num_peaks?: number | null;
        };
        /**
         * SpeciesStats
         * @description 物种统计
         */
        SpeciesStats: {
            /** Species Id */
            species_id: number;
            /** Species Name */
            species_name: string;
            /**
             * Gene Count
             * @description 基因数量
             */
            gene_count: number;
            /**
             * Lncrna Count
             * @description lncRNA数量
             */
            lncrna_count: number;
            /**
             * Protein Coding Count
             * @description protein_coding基因数量
             */
            protein_coding_count: number;
            /**
             * Regulation Count
             * @description 调控关系数量
             */
            regulation_count: number;
        };
        /**
         * TopDisease
         * @description Top疾病（按关联基因数量）
         */
        TopDisease: {
            /** Trait Id */
            trait_id: number;
            /** Trait Name */
            trait_name: string;
            /** Trait Category */
            trait_category: string | null;
            /** Gene Count */
            gene_count: number;
            /** Lncrna Count */
            lncrna_count: number;
        };
        /**
         * TopGene
         * @description Top基因（按调控数量）
         */
        TopGene: {
            /** Gene Id */
            gene_id: number;
            /** Core Id */
            core_id: number;
            /** Gene Name */
            gene_name: string | null;
            /** Gene Type */
            gene_type: string;
            /** Regulation Count */
            regulation_count: number;
            /** Species Name */
            species_name: string;
        };
        /**
         * TraitDetail
         * @description 性状/疾病详细信息
         */
        TraitDetail: {
            /** Trait Id */
            trait_id: number;
            /** Trait Name */
            trait_name: string;
            /** Trait Category */
            trait_category?: string | null;
            /** Description */
            description?: string | null;
            /** Trait Doid */
            trait_doid?: string | null;
            /**
             * Gene Count
             * @description 关联基因数量
             * @default 0
             */
            gene_count: number;
            /**
             * Lncrna Count
             * @description 关联lncRNA数量
             * @default 0
             */
            lncrna_count: number;
        };
        /**
         * TraitGeneAssociationDetail
         * @description 性状-基因关联详细信息
         */
        TraitGeneAssociationDetail: {
            /** Association Id */
            association_id: number;
            /** Core Id */
            core_id: number;
            /** Gene Name */
            gene_name?: string | null;
            /** Gene Type */
            gene_type: string;
            /** Trait Id */
            trait_id: number;
            /** Trait Name */
            trait_name: string;
            /** Trait Category */
            trait_category?: string | null;
            /** Ontology Id */
            ontology_id: number;
            /** Ontology Name */
            ontology_name: string;
            /** Ontology Type */
            ontology_type?: string | null;
            /** Odds Ratio */
            odds_ratio?: string | null;
            /** Fdr */
            fdr?: string | null;
            /** Trait Snp Pvalue */
            trait_snp_pvalue?: string | null;
            /** Ontology Mw Pvalue */
            ontology_mw_pvalue?: string | null;
            /** Ontology Fold Enrichment */
            ontology_fold_enrichment?: string | null;
            /** Literature Support */
            literature_support?: boolean | null;
            /** Evidence Species Id */
            evidence_species_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_genes_api_v1_genes_get: {
        parameters: {
            query?: {
                /** @description 页码 */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
                /** @description 基因类型（lncRNA/protein_coding） */
                gene_type?: string | null;
                /** @description 物种ID */
                species_id?: number | null;
                /** @description 染色体 */
                chromosome?: string | null;
                /** @description 搜索关键词（基因名/ID） */
                search?: string | null;
                /** @description 是否有调控关系 */
                has_regulation?: boolean | null;
                /** @description 最小调控数量 */
                min_regulation_count?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_GeneListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gene_detail_api_v1_genes__gene_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gene_orthologs_api_v1_genes__gene_id__orthologs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrthologInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regulations_api_v1_regulations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 物种ID */
                species_id?: number | null;
                /** @description lncRNA基因ID */
                lncrna_gene_id?: number | null;
                /** @description 靶基因ID */
                target_gene_id?: number | null;
                /** @description 最小结合亲和力 */
                min_ba?: number | null;
                /** @description 靶基因染色体 */
                chromosome?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RegulationListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regulation_detail_api_v1_regulations__regulation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regulation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gene_regulations_api_v1_regulations_gene__gene_id__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                min_ba?: number | null;
            };
            header?: never;
            path: {
                gene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RegulationListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diseases_api_v1_diseases_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 疾病分类 */
                trait_category?: string | null;
                /** @description 搜索关键词 */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TraitDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disease_detail_api_v1_diseases__trait_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trait_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disease_genes_api_v1_diseases__trait_id__genes_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 基因类型过滤 */
                gene_type?: string | null;
            };
            header?: never;
            path: {
                trait_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TraitGeneAssociationDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gene_disease_associations_api_v1_diseases_gene__gene_id__associations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraitGeneAssociationDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_stats_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewStats"];
                };
            };
        };
    };
    get_top_genes_api_v1_stats_top_genes_get: {
        parameters: {
            query?: {
                /** @description 返回数量 */
                limit?: number;
                /** @description 基因类型过滤 */
                gene_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopGene"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_diseases_api_v1_stats_top_diseases_get: {
        parameters: {
            query?: {
                /** @description 返回数量 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopDisease"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conserved_regulations_api_v1_stats_conserved_regulations_get: {
        parameters: {
            query?: {
                /** @description 最少保守物种数 */
                min_species?: number;
                /** @description 返回数量 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConservedRegulation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gene_network_api_v1_network_gene__gene_id__get: {
        parameters: {
            query?: {
                /** @description 限制物种 */
                species_id?: number | null;
                /** @description 最小结合亲和力 */
                min_ba?: number | null;
                /** @description 最大距离（bp） */
                max_distance?: number | null;
                /** @description 网络深度（1或2层） */
                depth?: number;
            };
            header?: never;
            path: {
                gene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_species_networks_api_v1_network_compare_get: {
        parameters: {
            query: {
                /** @description lncRNA基因ID（human） */
                lncrna_gene_id: number;
                /** @description 最小结合亲和力 */
                min_ba?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
